---
title: "Assignment 2"
author: "Karim Veljee"
format: 
  html:
    toc: true
    theme: "flatly"
    highlight-style: "tango"
    number-sections: true
---

## Murrell01.R

```{r}

### Paul Murrell's R examples (selected)

## Start plotting from basics 
# Note the order
plot(pressure, pch=20)
text(150, 600, 
     "Pressure (mm Hg)\nversus\nTemperature (Celsius)")

#  Examples of standard high-level plots 
#  In each case, extra output is also added using low-level 
#  plotting functions.
# 

# Setting the parameter (3 rows by 2 cols)
par(mfrow=c(3, 2))

# Scatterplot
# Note the incremental additions

x <- c(0.5, 2, 4, 8, 12, 16)
y1 <- c(1, 1.3, 1.9, 3.4, 3.9, 4.8)
y2 <- c(4, .8, .5, .45, .4, .3)

# Setting label orientation, margins c(bottom, left, top, right) & text size
par(las=1, mar=c(4, 4, 2, 4), cex=.7) 
plot.new()
plot.window(range(x), c(0, 6))
lines(x, y1)
lines(x, y2)
points(x, y1, pch=16, cex=3) 
points(x, y2, pch=21, bg="lightblue", cex=2)
par(col="gray50", fg="gray50", col.axis="gray50")
axis(1, at=seq(0, 16, 4)) # What is the first number standing for? The first number in the axis() function stands for the side of the plot where the axis is drawn. 1 is the bottom, 2 is the left, 3 is top and 4 is the right side.
axis(2, at=seq(0, 6, 2))
axis(4, at=seq(0, 6, 2))
box(bty="u")
mtext("Travel Time (s)", side=1, line=2, cex=0.8)
mtext("Responses per Travel", side=2, line=2, las=0, cex=0.8)
mtext("Responses per Second", side=4, line=2, las=0, cex=0.8)
text(4, 5, "Bird 131")
par(mar=c(5.1, 4.1, 4.1, 2.1), col="black", fg="black", col.axis="black")

# Histogram
# Random data
Y <- rnorm(50)
# Make sure no Y exceed [-3.5, 3.5]
Y[Y < -3.5 | Y > 3.5] <- NA # Selection/set range
x <- seq(-3.5, 3.5, .1)
dn <- dnorm(x)
par(mar=c(4.5, 4.1, 3.1, 0))
hist(Y, breaks=seq(-3.5, 3.5), ylim=c(0, 0.5), 
     col="gray80", freq=FALSE)
lines(x, dnorm(x), lwd=2)
par(mar=c(5.1, 4.1, 4.1, 2.1))

# Barplot
par(mar=c(2, 3.1, 2, 2.1)) 
midpts <- barplot(VADeaths, 
                  col=gray(0.1 + seq(1, 9, 2)/11), 
                  names=rep("", 4))
mtext(sub(" ", "\n", colnames(VADeaths)),
      at=midpts, side=1, line=0.5, cex=0.5)
text(rep(midpts, each=5), apply(VADeaths, 2, cumsum) - VADeaths/2,
     VADeaths, 
     col=rep(c("white", "black"), times=3:2), 
     cex=0.8)
par(mar=c(5.1, 4.1, 4.1, 2.1))  

# Boxplot
par(mar=c(3, 4.1, 2, 0))
boxplot(len ~ dose, data = ToothGrowth,
        boxwex = 0.25, at = 1:3 - 0.2,
        subset= supp == "VC", col="white",
        xlab="",
        ylab="tooth length", ylim=c(0,35))
mtext("Vitamin C dose (mg)", side=1, line=2.5, cex=0.8)
boxplot(len ~ dose, data = ToothGrowth, add = TRUE,
        boxwex = 0.25, at = 1:3 + 0.2,
        
        subset= supp == "OJ")
legend(1.5, 9, c("Ascorbic acid", "Orange juice"), 
       fill = c("white", "gray"), 
       bty="n")
par(mar=c(5.1, 4.1, 4.1, 2.1))

# Persp
x <- seq(-10, 10, length= 30)
y <- x
f <- function(x,y) { r <- sqrt(x^2+y^2); 10 * sin(r)/r }
z <- outer(x, y, f)
z[is.na(z)] <- 1
# 0.5 to include z axis label
par(mar=c(0, 0.5, 0, 0), lwd=0.5)
persp(x, y, z, theta = 30, phi = 30, 
      expand = 0.5)
par(mar=c(5.1, 4.1, 4.1, 2.1), lwd=1)

# Piechart
par(mar=c(0, 2, 1, 2), xpd=FALSE, cex=0.5)
pie.sales <- c(0.12, 0.3, 0.26, 0.16, 0.04, 0.12)
names(pie.sales) <- c("Blueberry", "Cherry",
                      "Apple", "Boston Cream", "Other", "Vanilla")
pie(pie.sales, col = gray(seq(0.3,1.0,length=6))) 


```

## Happy Planet Data

```{r}

library(ggplot2)
library(readxl)
hpd <- read_excel("C:/Users/kxi220002/Downloads/HPI_2024_public_dataset.xlsx", 
    sheet = "1. All countries", range = "A9:L158")
View(hpd)
```

```{r}

#Scatterplot

ggplot(hpd, aes_string("`Population (thousands)`", "`Carbon Footprint (tCO2e)`")) +
  geom_point() +
  ggtitle("Population vs Carbon Footprint") +
  xlab("Population (thousands)") +
  ylab("Carbon Footprint (tCO2e)")
```

```{r}

#Histogram

ggplot(hpd, aes_string("`GDP per capita ($)`" )) +
  geom_histogram(color = "black") +
  ggtitle("Frequency of GDP Per Capita") +
  xlab("GDP per capita ($)") +
  ylab("Frequency")
```

```{r}

#LinePlot

ggplot(hpd, aes_string("`Carbon Footprint (tCO2e)`", "`HPI`" )) +
  geom_line() +
  ggtitle("Carbon Footprint vs HPI") +
  xlab("Carbon Footprint(tCO2e)") +
  ylab("Happy Planet Index(HPI")
```

```{r}

#Box Plot

ggplot(hpd, aes(x = factor(Continent), y = `Life Expectancy (years)`, fill = 
factor(Continent))) +
  geom_boxplot() +
  ggtitle("Population vs Carbon Footprint") +
  xlab("Population (thousands)") +
  ylab("Carbon Footprint (tCO2e)")
```

```{r}

#Bar Plot

top10HPI <- hpd[order(-hpd$HPI),][1:10,]
ggplot(top10HPI, aes(x = reorder(Country, HPI), y = HPI, fill = Country)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(x = "Country", y = "HPI", title = "Top 10 Countries by HPI")
```

```{r}

#Perspective Plot

x <- seq(-10, 10, length=30)
y <- x
# Define the function for z values
f <- function(x, y) {
 r <- sqrt(x^2 + y^2)
 z <- sin(r) / r
 z[is.na(z)] <- 1 # Handle NaN values
 return(z)
}
# Create the z matrix
z <- outer(x, y, f)
# Create the 3D perspective plot
persp(x, y, z, theta = 30, phi = 30, 
 expand = 0.5, col="green", border="black",
 xlab="X", ylab="Y", zlab="Z")
```

```{r}

# Pie Chart

continent_counts <- table(hpd$`Continent`)
pie(continent_counts, main="Pie chart of Continent distribution")

```
